# Generated by Django 4.2.20 on 2025-04-08 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0019_submissionmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejudge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100, verbose_name='Comment for rejudge e.g. reason why it was needed')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Time rejudge was issued')),
            ],
        ),
        migrations.CreateModel(
            name='RejudgeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejudge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rejudgemgr.rejudge')),
                ('rj_former', models.ManyToManyField(related_name='rj_former', to='contests.submissionreport', verbose_name='Submission report(s) that were status=ACTIVE before rejudge (status=SUPERSEDED after)')),
                ('rj_newer', models.ManyToManyField(blank=True, related_name='rj_newer', to='contests.submissionreport', verbose_name='List of submission reports created and made status=ACTIVE after rejudge')),
                ('submit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.submission')),
            ],
            options={
                'unique_together': {('rejudge', 'submit')},
            },
        ),
    ]
